name: Build and Publish HyperBEAM Docker Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Commit SHA or tag (from HyperBEAM repo) to build the image from.'
        required: true
env:
  IMAGE_NAME: hyperbeam-docker

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build image
        run: |
          docker build . \
            --file geneis_wasm.Dockerfile \
            --tag $IMAGE_NAME \
            --label "runnumber=${GITHUB_RUN_ID}" \
            --build-arg VERSION=${{ github.event.inputs.version }}

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=$(echo "${{ github.event.inputs.version }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.event.inputs.version }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # Use Docker `latest` tag convention
          [ "$VERSION" == "main" ] && VERSION=stage
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$GITHUB_SHA
          docker push $IMAGE_ID:$GITHUB_SHA
